# This workflow will run tests using node and then publish a package to https://registry.npmjs.org

name: NPM Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test-and-coverage:
    name: Test And Coverage on ${{env.GITHUB_REF_NAME}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      
  publish:
    name: Publish on ${{env.GITHUB_REF_NAME}}
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    needs: test-and-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
